academics = [
    (
        href="https://doi.org/10.1002/pssb.202300310",
        image="/assets/academics/202310_gqd.png",
        title="Investigation of Rod-Shaped Single-Graphene Quantum Dot",
        subtitle="Physica Status Solidi (b)",
        intro="""In recent years, there has been a resurgence of interest in graphene quantum dots (i.e., large polycyclic aromatic hydrocarbons) in particular due to their interesting properties as single-quantum emitters. Herein, a thorough study of a graphene quantum dot made of 96 carbon atoms in a D<sub>2h</sub> symmetry is reported. In particular, experiments at the single-molecule level reveal that this graphene quantum dot structure is a bright and photostable single-photon emitter at room temperature. Finally, a statistical study of the emission wavelength as a function of the graphene quantum dot concentration highlights the high purity and degree of control on the samples.""",
        date=Date("18-10-2023", dateformat"d-m-y"),
        site="DOI:10.1002/pssb.202300310",
        tags=["English", "Spectroscopy", "Graphene Quantum Dots"],
        highlight=true,
    ),
    (
        href="https://doi.org/10.1038/s41467-023-40376-w",
        image="/assets/academics/202308_gqd.png",
        title="Interplay of structure and photophysics of individualized rod-shaped graphene quantum dots with up to 132 sp² carbon atoms",
        subtitle="Nature Communications",
        intro="""Nanographene materials are promising building blocks for the growing field of low-dimensional materials for optics, electronics and biophotonics applications. In particular, bottom-up synthesized 0D graphene quantum dots show great potential as single quantum emitters. To fully exploit their exciting properties, the graphene quantum dots must be of high purity; the key parameter for efficient purification being the solubility of the starting materials. Here, we report the synthesis of a family of highly soluble and easily processable rod-shaped graphene quantum dots with fluorescence quantum yields up to 94%. This is uncommon for a red emission. The high solubility is directly related to the design of the structure, allowing for an accurate description of the photophysical properties of the graphene quantum dots both in solution and at the single molecule level. These photophysical properties were fully predicted by quantum-chemical calculations.""",
        date=Date("07-08-2023", dateformat"d-m-y"),
        site="DOI:10.1038/s41467-023-40376-w",
        tags=["English", "Spectroscopy", "Graphene Quantum Dots", "Nature Communications"],
        highlight=true,
    ),
    (
        href="https://doi.org/10.1039/D2CC01028C",
        image="/assets/academics/202204_nanocrystals.png",
        title="Synthesis method of highly calibrated CsPbBr3 nanocrystals perovskites by soft chemistry",
        subtitle="Chemical Communications (Royal Society of Chemistry)",
        intro="""A new synthesis method of highly calibrated CsPbBr3 nanocrystals perovskites is described and analyzed using High-Resolution Scanning Transmission Electron Microscopy. This new method based on soft chemistry leads to the large-scale production of nanocrystals. Such monodisperse nanocrystals allow for the deposition of homogeneous films which provides new opportunities for the next generation of optoelectronic devices.""",
        date=Date("19-04-2022", dateformat"d-m-y"),
        site="DOI:10.1039/D2CC01028C",
        tags=["English", "Perovskites", "Spectroscopy", "Nano-chemistry", "Chemical Communications"],
        highlight=true,
    ),
   ]
